# Site settings
title: Gábor Molnár
header-img: img/home-bg.jpg
email: gabor@molnar.es
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: 
url: "http://gabor.molnar.es"
twitter_username: molnar_g
github_username:  molnarg
facebook_username:  mr.gabor.molnar

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
